language: node_js
sudo: false

node_js:
  - "6.11.3"

services:
  - mongodb

install:
  - npm install

env:
  - NODE_ENV=test

script:
  - npm run codecov

before_deploy:
  - openssl aes-256-cbc -K $encrypted_aa2fbc2a7417_key -iv $encrypted_aa2fbc2a7417_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  # deploy develop to the staging environment
  - provider: script
    script: scripts/deploy.sh staging
    on:
      branch: develop
  # deploy master to production
  - provider: script
    script: scripts/deploy.sh production
    on:
      branch: master
