# project_name=podcloud-feeds
version: "3"
services:
  feeds: # scale=3
    image: podshows/podcloud-feeds:latest
    networks:
      - traefik
      - podcloud
    volumes:
      - ./config:/usr/src/app/config
    restart: always
    labels:
      traefik.enable: true
      traefik.backend: "podcloud-feeds"
      traefik.frontend.priority: 500
      traefik.frontend.rule: "HostRegexp:feeds.podcloud.fr"

networks:
  podcloud:
    external: true
  traefik:
    external: true
