# project_name=podcloud
version: "3"
services:
  feeds: # scale=3
    image: podshows/podcloud-feeds:latest
    networks:
      - traefik
    volumes:
      - ./config:/usr/src/app/config
    labels:
      traefik.enable: true
      traefik.backend: "podcloud-feeds"
      traefik.frontend.rule: "HostRegexp:feeds.podcloud.fr"

networks:
  traefik:
    external: true
