version: "3"
services:
  feeds: # scale=3
    image: "podcloud-feeds"
    build: .
    volumes:
      - ./config:/usr/src/app/config
    labels:
        traefik.backend: "podcloud-feeds"
        traefik.frontend: "podcloud-feeds"
        traefik.frontend.rule: "HostRegexp:feeds.podcloud.fr"
