# project_name=podcloud-feeds
version: "3.4"
services:
  feeds:
    image: "podcloud-feeds"
    build:
      context: .
      target: runner
    volumes:
      - .:/usr/src/app
    networks:
      - traefik
      - podcloud
    environment:
      - DEBUG=podcloud-feeds:*
    labels:
      traefik.frontend.rule: "HostRegexp:feeds.{host:podcloud}.test"
      traefik.frontend.priority: 500
    extra_hosts:
      - "dave:192.168.10.40"

networks:
  podcloud:
    external: true
  traefik:
    external: true
